# Site settings
baseurl = "antonitong.github.io"
languageCode = "en"
publishDir = "docs"
title = "Antoni Tong"
theme = "hugo-theme-cactus-plus"
googleAnalytics = "your_google_analytics_id"
# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
hasCJKLanguage = false

[params]
	author = "Antoni Tong"
	description = "Site Description"
	bio = "Energy Research at UC San Diego"

	twitter = "your_twitter_id"
	facebook = "your_facebook_id"

	enableRSS = true
	enableToc = true

	enableDisqus = true
	disqusShortname = "your_disqus_short_name"


	enableSummary = false
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = false


	enableGoogleAnalytics = true
enableBaiduAnalytics = false
	# Set the value to your baidu analysis code if you want to use baidu analytics
	baiduAnalytics = 'your_baidu_analysis_code'

	enableTwitterCard = false
	# The url for twitter card image, default is avatar.png in static/images directory
	twitterCardImage = ""

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	blog = ""
	work_notes =""
	#subscribe = ""


	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# show latest posts in single page
	showLatestPosts = false
	readMore = ""

	# Share
	enableShare = true
	tweet = ""
	share = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""


# Add additional social link entries underneath
[social]
	linkedin-square = "www.linkedin.com/in/antonitong"
	github-square = "https://www.github.com/antonitong"
